# Generated by Django 3.0.5 on 2020-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfrequest',
            name='time_elapsed',
            field=models.IntegerField(null=True),
        ),
    ]
