# Generated by Django 3.0.7 on 2020-09-18 12:17
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, transaction


def migrate_requests(apps, schema_editor):
    PDFRequest = apps.get_model('pdf', 'PDFRequest')
    Category = apps.get_model('category', 'Category')
    locales = {code: Category.objects.get(name=name) for code, name in settings.LANGUAGES}
    with transaction.atomic():
        for request in PDFRequest.objects.all():
            request.category = locales[request.locale]
            request.save()


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200918_1217'),
        ('backend', '0007_auto_20200918_1217'),
        ('pdf', '0003_auto_20200808_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pdfrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category'),
        ),
        migrations.RunPython(migrate_requests),
        migrations.AddField(
            model_name='pdfrequest',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pdfrequest',
            name='status',
            field=models.CharField(choices=[('QU', 'Queued'), ('PR', 'In progress'), ('DO', 'Done'), ('FA', 'Failed')], default='QU', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='pdfrequest',
            constraint=models.CheckConstraint(check=models.Q(('type', 'MA'), ('category__isnull', False), _connector='OR'), name='automated_category_present'),
        ),
        migrations.AddField(
            model_name='pdfsong',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.PDFRequest'),
        ),
        migrations.AddField(
            model_name='pdfsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Song'),
        ),
        migrations.RemoveField(
            model_name='pdfrequest',
            name='songs',
        ),
        migrations.AddField(
            model_name='pdfrequest',
            name='songs',
            field=models.ManyToManyField(through='pdf.PDFSong', to='backend.Song'),
        ),
        migrations.AlterUniqueTogether(
            name='pdfsong',
            unique_together={('song_number', 'request', 'song')},
        ),
        migrations.AlterModelOptions(
            name='pdfrequest',
            options={'ordering': ['-update_date']},
        ),
    ]
