# Generated by Django 3.1.1 on 2020-09-19 21:30

from django.db import migrations, models
import pdf.storage


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_request_20200918_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfrequest',
            name='file',
            field=models.FileField(null=True, storage=pdf.storage.DateOverwriteStorage(), upload_to=''),
        ),
    ]
