# Generated by Django 3.2.5 on 2021-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_alter_pdfsong_song_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfrequest',
            name='margin',
            field=models.FloatField(default=0, help_text='Margins for title image, might be needed for some printers', verbose_name='Title Image margins'),
        ),
    ]
