# Generated by Django 4.0.7 on 2022-09-26 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0016_pdfrequest_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfrequest",
            name="show_title",
        ),
    ]
