# Generated by Django 4.2.5 on 2023-09-10 06:47

from django.db import migrations, models
import django.db.models.deletion


def attach_to_tenant(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Tenant = apps.get_model("tenants", "Tenant")
    PDFRequest = apps.get_model("pdf", "PDFRequest")
    db_alias = schema_editor.connection.alias

    default_tenant = Tenant.objects.using(db_alias).first()
    requests = PDFRequest.objects.using(db_alias).all()
    for request in requests:
        request.tenant = default_tenant

    PDFRequest.objects.using(db_alias).bulk_update(requests, ["tenant"])


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("pdf", "0020_remove_pdfrequest_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfrequest",
            name="tenant",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant", null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(attach_to_tenant),
        migrations.AlterField(
            model_name="pdfrequest",
            name="tenant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
        ),
    ]
