# Generated by Django 4.2.5 on 2023-09-20 12:33

from django.db import migrations, models
import pdf.models.request
import pdf.storage


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0022_alter_pdfrequest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfrequest",
            name="file",
            field=models.FileField(
                null=True, storage=pdf.storage.DateOverwriteStorage(), upload_to=pdf.models.request.upload_path
            ),
        ),
    ]
