# Generated by Django 5.0 on 2024-01-20 16:55

import django.db.models.deletion
import pdf.models.file
import pdf.storage
from django.db import migrations, models


def migrate_category(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    PDFRequest = apps.get_model("pdf", "PDFRequest")
    db_alias = schema_editor.connection.alias

    for request in PDFRequest.objects.using(db_alias).filter(category__isnull=False):
        request.categoryID = request.category.id
        request.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0024_alter_pdfrequest_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfrequest",
            name="categoryID",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="pdfrequest",
            name="tenant",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
        ),
        migrations.RunPython(migrate_category),
        migrations.RemoveConstraint(
            model_name="pdfrequest",
            name="automated_category_present",
        ),
        migrations.RemoveField(
            model_name="pdfrequest",
            name="category",
        ),
    ]
