# Generated by Django 5.0 on 2024-01-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_rename_prerendered_pdf_song_prerendered_and_more"),
        ("pdf", "0026_pdffile"),
        ("tenants", "0004_alter_tenant_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdfrequest",
            options={
                "ordering": ["-last_generated"],
                "verbose_name": "PDFRequest",
                "verbose_name_plural": "PDFRequests",
            },
        ),
        migrations.AddConstraint(
            model_name="pdfrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", "MA"), ("tenant__isnull", False)),
                    models.Q(("type", "EV"), ("tenant__isnull", True)),
                    _connector="OR",
                ),
                name="has_tenant",
            ),
        ),
    ]
