# Generated by Django 5.0.2 on 2024-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0027_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdffile",
            options={"verbose_name": "PDFFile", "verbose_name_plural": "PDFFile"},
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="locale",
            field=models.CharField(
                choices=[("en", "English"), ("cs", "Česky")],
                help_text="Language to be used in the generated PDF",
                max_length=5,
                verbose_name="Language",
            ),
        ),
    ]
