# Generated by Django 5.1.4 on 2024-12-20 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_song_categories"),
        ("pdf", "0028_delete_pdfrequest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PDFSong2",
            new_name="PDFSong",
        ),
    ]
