# Generated by Django 6.0 on 2026-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_song_categories"),
        ("pdf", "0029_rename_pdfsong2_pdfsong"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pdfsong",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="pdfsong",
            constraint=models.UniqueConstraint(
                fields=("song_number", "request", "song"), name="pdfsong_number_request_song_uniq"
            ),
        ),
    ]
