# Generated by Django 3.2.9 on 2021-12-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25, verbose_name='Key')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
