# Generated by Django 3.2.9 on 2021-12-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daystatistic',
            name='amount',
        ),
        migrations.AddField(
            model_name='daystatistic',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='Hits'),
        ),
    ]
