# Generated by Django 5.1.4 on 2024-12-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_daystatistic_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daystatistic",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
