# Generated by Django 6.0 on 2026-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_alter_daystatistic_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daystatistic",
            name="hits",
            field=models.IntegerField(db_default=models.Value(0), verbose_name="Hits"),
        ),
    ]
