# Generated by Django 4.2.5 on 2023-09-10 06:47
from django.conf import settings
from django.db import migrations, models
from django.urls import reverse_lazy


def create_default_tenant(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Tenant = apps.get_model("tenants", "Tenant")
    Category = apps.get_model("category", "Category")
    db_alias = schema_editor.connection.alias
    category = Category.objects.using(db_alias).all().first()
    Tenant.objects.using(db_alias).create(
        hostname=settings.TENANT_HOSTNAME,
        name=settings.TENANT_NAME,
        display_name=settings.SITE_NAME,
        index_redirect=reverse_lazy("category:index", kwargs={"slug": category.slug}),
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0010_alter_song_categories"),
        ("category", "0008_category_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hostname",
                    models.CharField(
                        help_text="The exact hostname for this Tenant",
                        max_length=64,
                        unique=True,
                        verbose_name="Hostname",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Internal name for this Tenant", max_length=32, verbose_name="Name"),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Title on the Main site", max_length=32, verbose_name="Title"),
                ),
                (
                    "index_redirect",
                    models.CharField(
                        help_text="Where should new tenant redirect from index page, usually a category slug",
                        max_length=32,
                        verbose_name="Index redirect path",
                    ),
                ),
                ("admins", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_default_tenant),
    ]
