# Generated by Django 4.2.5 on 2023-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="all_songs_category",
            field=models.BooleanField(
                default=True,
                help_text="True, if all songs category should be added to navigation",
                verbose_name="All Songs",
            ),
        ),
    ]
