# Generated by Django 5.1.4 on 2024-12-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_alter_tenant_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link", models.URLField(verbose_name="Link URL")),
                ("display_name", models.CharField(blank=True, max_length=64, null=True, verbose_name="Display Name")),
            ],
        ),
        migrations.AddField(
            model_name="tenant",
            name="links",
            field=models.ManyToManyField(to="tenants.link"),
        ),
    ]
