# Generated by Django 5.1.4 on 2024-12-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_link_tenant_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="links",
            field=models.ManyToManyField(blank=True, to="tenants.link"),
        ),
    ]
