# Generated by Django 2.2.7 on 2019-11-09 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube Link'),
        ),
        migrations.AlterField(
            model_name='song',
            name='locale',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('([a-z]{2}|[a-z]{2}_[a-z]{2})', 'Your language code should in format ab_cd')], verbose_name='Language'),
        ),
    ]
