# Generated by Django 2.2.7 on 2019-11-09 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191109_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_number',
        ),
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
