# Generated by Django 2.2.7 on 2019-11-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191109_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='capo',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Capo'),
        ),
        migrations.AlterField(
            model_name='song',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('cs', 'Czech')], default='Czech', max_length=5, verbose_name='Language'),
        ),
    ]
