# Generated by Django 3.0.7 on 2020-08-09 05:29
from django.conf import settings
from django.db import migrations, models


def migrate_locales(apps, schema_editor):
    Song = apps.get_model("backend", "Song")
    Category = apps.get_model("category", "Category")
    locales = map(lambda x: x["locale"], Song.objects.values("locale").distinct())
    for locale in locales:
        category = Category(name=locale, generate_pdf=True, slug=locale, locale=locale)
        category.save()
        for song in Song.objects.filter(locale=locale):
            song.categories.add(category)
            song.save()

    for code, name in settings.LANGUAGES:
        if Category.objects.filter(name=code).exists():
            category = Category.objects.get(name=code)
            category.name = name
            category.save()
        else:
            category = Category(name=name, generate_pdf=True, slug=code, locale=code)
            category.save()


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
        ("backend", "0005_auto_20191124_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="categories",
            field=models.ManyToManyField(to="category.Category"),
        ),
        migrations.RunPython(migrate_locales),
        migrations.RemoveField(
            model_name="song",
            name="locale",
        ),
    ]
