# Generated by Django 6.0 on 2026-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_song_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="capo",
            field=models.PositiveSmallIntegerField(db_default=models.Value(0), verbose_name="Capo"),
        ),
    ]
