# Generated by Django 3.2.5 on 2021-08-01 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_auto_20200925_1902"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Songbook", "verbose_name_plural": "Songbooks"},
        ),
    ]
