# Generated by Django 4.0.5 on 2022-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0005_category_filename_category_image_category_margin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="link",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Link to include in the PDF",
                max_length=300,
                verbose_name="Link",
            ),
        ),
    ]
