# Generated by Django 4.2.5 on 2023-09-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("category", "0009_category_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=25, verbose_name="URL pattern"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("tenant", "slug"), ("tenant", "name")},
        ),
    ]
