# Generated by Django 5.1.4 on 2024-12-20 18:29

import django.db.models.deletion
from django.db import migrations, models


def recreate_categories(apps, schema_editor):
    Category = apps.get_model("category", "Category")
    NewCategory = apps.get_model("category", "Category2")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias

    for category in Category.objects.using(db_alias).all():
        new_category = NewCategory()
        new_category.polymorphic_ctype_id = ContentType.objects.get_for_model(Category).pk
        for field in [
            "pk",
            "filename",
            "public",
            "locale",
            "title",
            "show_date",
            "image",
            "margin",
            "link",
            "generate_pdf",
            "tenant_id",
            "slug",
            "name",
        ]:
            setattr(new_category, field, getattr(category, field))
        new_category.save()


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0012_alter_category_link"),
        ("pdf", "0026_pdftemplate_pdffile_alter_pdfrequest_options_and_more"),
        ("tenants", "0005_link_tenant_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category2",
            fields=[
                (
                    "pdftemplate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pdf.pdftemplate",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(max_length=25, verbose_name="URL pattern")),
                (
                    "generate_pdf",
                    models.BooleanField(
                        help_text="Should the PDF file be automatically generated when a song changes?",
                        verbose_name="PDF generation",
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "unique_together": {("tenant", "name"), ("tenant", "slug")},
            },
            bases=("pdf.pdftemplate",),
        ),
        migrations.RunPython(recreate_categories),
    ]
