# Generated by Django 5.1.4 on 2024-12-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_alter_song_categories"),
        ("category", "0013_category2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
