# Generated by Django 5.1.4 on 2024-12-20 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_song_categories"),
        ("category", "0014_delete_category"),
        ("pdf", "0026_pdftemplate_pdffile_alter_pdfrequest_options_and_more"),
        ("tenants", "0005_link_tenant_links"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category2",
            new_name="Category",
        ),
    ]
