# Generated by Django 6.0 on 2026-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0016_alter_category_generate_pdf_alter_category_slug"),
        ("pdf", "0029_rename_pdfsong2_pdfsong"),
        ("tenants", "0007_alter_tenant_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("tenant", "slug"), name="category_tenant_slug_uniq"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("tenant", "name"), name="category_tenant_name_uniq"),
        ),
    ]
